name: conta_certa
description: "A Flutter project of an app that helps organize finances from events or get-together"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_platform_widgets: ^9.0.0
  device_preview: ^1.3.1
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.0
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  fluttertoast: ^8.2.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/conta_certa_logo.png
