name: conta_certa
description: "A Flutter project of an app that helps organize finances from events or get-together"
publish_to: 'none'
version: 0.1.3-beta.1+4

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_platform_widgets: ^9.0.0
  device_preview: ^1.3.1
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.0
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  fluttertoast: ^8.2.12
  intl: ^0.20.2
  flutter_launcher_icons: ^0.14.4
  url_launcher: ^6.2.5
  package_info_plus: ^8.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/conta_certa_logo.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/conta_certa_logo_ios.png"
  
  adaptive_icon_background: "#339966"
  adaptive_icon_foreground: "assets/images/conta_certa_logo_android_foreground.png"